### ISSUE TITLE
Error after saying loaded one event 

### ISSUE THREAD

**Issue by Gang-gg** [LewdHuTao/Lavalink-Status#19]
It says loaded one event then giving error missing permission here is a attachment for more clarification 
![Screenshot_2023_0824_231803](https://github.com/LewdHuTao/Lavalink-Status/assets/132687735/176853b9-31a4-4ff1-a9a8-cfd777a90805)

**Comment by LewdHuTao** [comment]
your bot is missing access, give your bot correct access

**Comment by Gang-gg** [comment]
Ohh thanks its worked perfectly fine i invited the bot with proper permission but while i was setting up it got kicked cause of not verified so i got error thanks for help man
