### ISSUE TITLE
Can we somehow have it track both v3 and v4 status 

### ISSUE THREAD

**Issue by anas-ike** [LewdHuTao/lavalink-status#22]
I have multiple LavaLink hosted of different versions v3 and v4 this code supports v4 but not v3 is there something by which we can make it support v3 too

**Comment by LewdHuTao** [comment]
Unfortunately it's not possible, but you can fetch both stats from v3 and v4 lavalink through HTTP requests. I'm not planning to update the code to make it support both v3 and v4, soon v3 lavalink will no longer maintain

**Comment by LewdHuTao** [comment]
You can still checkout the other branch as it supports lavalink v3

**Comment by Kefisto** [comment]
Печально, что это не поддерживает обе версии.

**Comment by anas-ike** [comment]
It's sad that it doesn't support both versions
